CREATE TABLE Users (
    UserID INT IDENTITY PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL
);

CREATE TABLE Rooms (
    RoomID INT IDENTITY PRIMARY KEY,
    RoomName NVARCHAR(50) NOT NULL
);

CREATE TABLE Messages (
    MessageID INT IDENTITY PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
    RoomID INT NOT NULL FOREIGN KEY REFERENCES Rooms(RoomID),
    MessageText NVARCHAR(MAX) NOT NULL,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE()
);
